### ISSUE TITLE
[Unity 5.3.3+] Light Shafts Not Working on OS X

### ISSUE THREAD

**Issue by MarcSteene** [robertcupisz/LightShafts#12]
The light shafts no longer work on Unity 5.3.3+, they are invisible :(

**Comment by Agilethief** [comment]
We're on 5.3.4 and the light shafts appear to be working fine.

**Comment by MarcSteene** [comment]
That's weird - they disappear for me after upgrading. I'll conduct some more tests.

**Comment by MarcSteene** [comment]
It seems to be working on Windows but not OS X (5.3.4).

**Comment by CandyFace** [comment]
Can confirm, Lightshafts doesn't work on OSX 10.11.3 with latest unity 5.3.4f1
getting these errors in console:

Shader error in 'Hidden/Raymarch': Can't find include file Shared.cginc (on opengl)

Compiling Vertex program with DIRECTIONAL_SHAFTS COLORED_ON ATTENUATION_CURVE_ON COOKIE_TEX_ON

Shader error in 'Hidden/Raymarch': Can't find include file Shared.cginc (on metal)

Compiling Vertex program with DIRECTIONAL_SHAFTS COLORED_ON ATTENUATION_CURVE_ON COOKIE_TEX_ON

Shader error in 'Hidden/Raymarch': failed to open source file: 'Shared.cginc' at line 15 (on glcore)

Compiling Vertex program with DIRECTIONAL_SHAFTS COOKIE_TEX_OFF ATTENUATION_CURVE_OFF COLORED_OFF

Shader error in 'Hidden/Raymarch': '' : Include callback failed at line 16 (on opengl)

Compiling Vertex program with DIRECTIONAL_SHAFTS COLORED_ON ATTENUATION_CURVE_ON COOKIE_TEX_ON

Shader error in 'Hidden/Raymarch': '' : Include callback failed at line 16 (on metal)

Compiling Vertex program with DIRECTIONAL_SHAFTS COLORED_ON ATTENUATION_CURVE_ON COOKIE_TEX_ON
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING SHADER_API_DESKTOP

**Comment by ludicch** [comment]
found the same problem, however i dont get any shader compile errors

**Comment by ryanstockau** [comment]
Same issue here, running Unity 5.3.4f1 Personal on Mac OS X 10.11.4. The light shafts were there a few weeks ago, but now show nothing. Any help would be appreciated!

**Comment by Agilethief** [comment]
To confirm, we found they did not work on Mac or Linux and as such have had to disable them, shame as they make our game look gorgeous.

**Comment by robertcupisz** [comment]
The latest should work now. Tested with Unity 5.4
