### ISSUE TITLE
No effect for mobile

### ISSUE THREAD

**Issue by MocanuMarius** [robertcupisz/LightShafts#15]
In the unity editor and player everything is ok, but on the actual mobile device it doesn't show at all. I tried fiddling with the lighting settings for mobile player and didn't come up to a solution. Is this restricted on mobile in anyway or am i just stupid ?

**Comment by robertcupisz** [comment]
Mobile support was newer implemented, or even tested. No reason why it can't work on mobile, other than it's pretty expensive, you'd have to get around the fact that some texture formats are missing and that it won't implement itself ;)

**Comment by MocanuMarius** [comment]
Roger. Thanks for the answer

**Comment by MocanuMarius** [comment]
@robertcupisz any idea what i need to learn in order to make it work on mobile ? The default light shafts from unity are not suitable since they occur post-processing..i only need to put some lights around some goddamn unlit 2d textures and i cannot find a solution that doesn't wreck the mobile framerate...i'm pretty sure your solution would work better. Right now there's no frame drop but neither the shafts displayed on maximum level performance :/

**Comment by robcupisz** [comment]
If you're referring to the simple radial-blur light shafts, then I doubt these here would be faster and certainly need more memory.

If you need an ultra-lightweight solution, maybe consider manually placed planes?

**Comment by MocanuMarius** [comment]
@robertcupisz you mean planes to just reflect light off them ? Well my light should wrap around some scenery element silhouettes like plains and valleys with no real rectangular structure or anything easy like that.

**Comment by robcupisz** [comment]
Semi-transparent planes with a light-shaft-like texture on them - an oldschool trick that works well if you don't have to see a correct volumetric shadow. As a bonus, you have artistic control over them.
