### ISSUE TITLE
LightShaft Banding

### ISSUE THREAD

**Issue by rodrigomas** [robertcupisz/LightShafts#16]
Hi, on Dark scenes it is possible to see the banding, even with higher resolutions.

Which shader you think I can change to reduce it (as you said dithering)?

Regards
Rodrigo

**Comment by robertcupisz** [comment]
Hi Rodrigo. Reducing banding is rather complex and takes some time to get right. I recommend the talk by Mikkel Gjøl to learn what's state-of-the-art in banding reduction nowadays. http://www.gdcvault.com/play/1023002/Low-Complexity-High-Fidelity-INSIDE
