### ISSUE TITLE
Works on VR?

### ISSUE THREAD

**Issue by pherting** [robertcupisz/LightShafts#17]
Hello and thank you for this great stuff!
I don't get it work on my VR Project with SteamVR and my HTC Vive.
In the unity Window it works great, but not on my Headset.. i don't see anything :(
Is there any workarround or something?

Thank you!

**Comment by pherting** [comment]
Sorry for my issue! But it works perfectly when you Change the Default camera to the Eye Camera from the CameraRig! ;)

Sorry for creating an issue... <3

**Comment by baptistepoligne** [comment]
Hi pherting !
Can you be more explicit ? I'd like to make it work too :)
