### ISSUE TITLE
Problem with forward doubleside shader

### ISSUE THREAD

**Issue by matumu20** [robertcupisz/LightShafts#21]
I have a problem with using LightShaft with “forward doubleside shader”.
I want to use a custom forward double side (cull off) shader for plane object lit by back light with LightShaft. If I make LightShaft enable, backside face became transparent. For several reasons, I can’t avoid using this forward shader (but render path is set deferred).
If I set deferred double side shader , it seems to be no problem. What is the reason of this problem and how can I fix?
(Unity5.5
![enabledlightshaft](https://cloud.githubusercontent.com/assets/8414506/22098142/10a69674-de68-11e6-8eea-c81661bc86c0.jpg)
![disabledlightshaft](https://cloud.githubusercontent.com/assets/8414506/22098143/10a804c8-de68-11e6-9513-ee520de99b31.jpg)

)

**Comment by robertcupisz** [comment]
Hey, so the object is not becoming transparent. It's just that it's not writing to _CameraDepthTexture, and that's where light shafts take the scene depth from. So if your shader is not writing to that texture (or writing to it too late, after light shafts had executed), then it's as if it doesn't exist from the point of view of the light shafts. So you have to make the shader execute before the light shafts and write its depth into _CameraDepthTexture. That's also why it works when you set it to deferred: it writes its depth earlier then, as part of the gbuffer generation.
