### ISSUE TITLE
Ambiguous Reference Exceptions

### ISSUE THREAD

**Issue by ahjohnstone** [robertcupisz/LightShafts#22]
A few ambiguous reference exceptions from the LightShaftsEditor js file are showing up Unity 5.5.2

![lightshafterrors](https://cloud.githubusercontent.com/assets/8761551/24575295/0a0f962e-165f-11e7-88e3-8dec23e33c62.JPG)

**Comment by robertcupisz** [comment]
Looks like you might have another script in your project also using the name LightShafts.

**Comment by TheDadaFactory** [comment]
You're totally right! My bad;)
