### ISSUE TITLE
Unity 4.6.3 & 4.6.4 on OSX not working

### ISSUE THREAD

**Issue by newyellow** [robertcupisz/LightShafts#6]
I tried this on Unity 4.6.3 & 4.6.4 both on OSX 10.10 and Windows 7.
Windows 7 worked fine, but OSX can't see the light beam, and 100% crash when switch to game view.
I tried this on mac last year and worked fine ( it was around unity 4.5.4 ).
Is it possible to make it work on OSX with unity 4.6.4 ?

**Comment by robertcupisz** [comment]
Should work now on osx.
